# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'push' && steps.filter.outputs.paths == 'src' }}

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Filter by paths
      id: filter
      uses: dorny/paths-filter@v2
      with:
        paths: |
          src/**
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm ci runs
      run: echo ${{steps,github}} npm ci
    - name: instaling dependcies
      run: npm i --force
    - name: bulding your app
      run: CI=false npm run build
